config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :order_items
  resources :orders
  resources :buyers
  resources :stock_transactions
  resources :warehouse_stocks
  resources :warehouses
  resources :stock_members
  resources :stocks
  resources :categories
  resources :products
  resources :sellers

  mount MailsViewer::Engine => '/delivered_mails'

  root 'home#index'

  devise_for :users

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  belongs_to :user

  has_many :buyers
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :seller
  belongs_to :buyer

  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :seller

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :seller
  belongs_to :category

  has_many :order_items
  has_many :stock_transactions
  has_many :warehouse_stocks
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  belongs_to :user

  has_many :orders
  has_many :order_items
  has_many :products
  has_many :stock_members
  has_many :stock_transactions
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user

  has_many :stock_members
  has_many :warehouses
  has_many :warehouse_stocks
end

app/models/stock_member.rb
class StockMember < ActiveRecord::Base
  belongs_to :stock
  belongs_to :seller
end

app/models/stock_transaction.rb
class StockTransaction < ActiveRecord::Base
  belongs_to :seller
  belongs_to :product
  belongs_to :origin_warehouse, class_name: "Warehouse", foreign_key: :origin_warehouse_id
  belongs_to :destination_warehouse, class_name: "Warehouse", foreign_key: :destination_warehouse_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :buyer
  has_one :seller
  has_many :stocks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  belongs_to :stock
  has_many :warehouse_stocks
end

app/models/warehouse_stock.rb
class WarehouseStock < ActiveRecord::Base
  belongs_to :stock
  belongs_to :product
  belongs_to :warehouse
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  before_action :set_seller, only: [:show, :edit, :update, :destroy]

  # GET /sellers
  # GET /sellers.json
  def index
    @sellers = Seller.all
  end

  # GET /sellers/1
  # GET /sellers/1.json
  def show
  end

  # GET /sellers/new
  def new
    @seller = Seller.new
  end

  # GET /sellers/1/edit
  def edit
  end

  # POST /sellers
  # POST /sellers.json
  def create
    @seller = Seller.new(seller_params)

    respond_to do |format|
      if @seller.save
        format.html { redirect_to @seller, notice: 'Seller was successfully created.' }
        format.json { render :show, status: :created, location: @seller }
      else
        format.html { render :new }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sellers/1
  # PATCH/PUT /sellers/1.json
  def update
    respond_to do |format|
      if @seller.update(seller_params)
        format.html { redirect_to @seller, notice: 'Seller was successfully updated.' }
        format.json { render :show, status: :ok, location: @seller }
      else
        format.html { render :edit }
        format.json { render json: @seller.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sellers/1
  # DELETE /sellers/1.json
  def destroy
    @seller.destroy
    respond_to do |format|
      format.html { redirect_to sellers_url, notice: 'Seller was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seller
      @seller = Seller.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seller_params
      params.require(:seller).permit(:user_id, :region, :address, :active, :raiting)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/sellers/_form.html.haml
= form_for @seller do |f|
  - if @seller.errors.any?
    #error_explanation
      %h2= "#{pluralize(@seller.errors.count, "error")} prohibited this seller from being saved:"
      %ul
        - @seller.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :region
    = f.text_field :region
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :active
    = f.check_box :active
  .field
    = f.label :raiting
    = f.number_field :raiting
  .actions
    = f.submit 'Save'

app/views/sellers/edit.html.haml
%h1 Editing seller

= render 'form'

= link_to 'Show', @seller
\|
= link_to 'Back', sellers_path

app/views/sellers/index.html.haml
%h1 Listing sellers

%table
  %thead
    %tr
      %th User
      %th Region
      %th Address
      %th Active
      %th Raiting
      %th
      %th
      %th

  %tbody
    - @sellers.each do |seller|
      %tr
        %td= seller.user_id
        %td= seller.region
        %td= seller.address
        %td= seller.active
        %td= seller.raiting
        %td= link_to 'Show', seller
        %td= link_to 'Edit', edit_seller_path(seller)
        %td= link_to 'Destroy', seller, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Seller', new_seller_path

app/views/sellers/new.html.haml
%h1 New seller

= render 'form'

= link_to 'Back', sellers_path

app/views/sellers/show.html.haml
%p#notice= notice

%p
  %b User:
  = @seller.user_id
%p
  %b Region:
  = @seller.region
%p
  %b Address:
  = @seller.address
%p
  %b Active:
  = @seller.active
%p
  %b Raiting:
  = @seller.raiting

= link_to 'Edit', edit_seller_path(@seller)
\|
= link_to 'Back', sellers_path