config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :order_items
  resources :orders
  resources :buyers
  resources :stock_transactions
  resources :warehouse_stocks
  resources :warehouses
  resources :stock_members
  resources :stocks
  resources :categories
  resources :products
  resources :sellers

  mount MailsViewer::Engine => '/delivered_mails'

  root 'home#index'

  devise_for :users

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  belongs_to :user

  has_many :buyers
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :seller
  belongs_to :buyer

  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :seller

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :seller
  belongs_to :category

  has_many :order_items
  has_many :stock_transactions
  has_many :warehouse_stocks
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  belongs_to :user

  has_many :orders
  has_many :order_items
  has_many :products
  has_many :stock_members
  has_many :stock_transactions
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user

  has_many :stock_members
  has_many :warehouses
  has_many :warehouse_stocks
end

app/models/stock_member.rb
class StockMember < ActiveRecord::Base
  belongs_to :stock
  belongs_to :seller
end

app/models/stock_transaction.rb
class StockTransaction < ActiveRecord::Base
  belongs_to :seller
  belongs_to :product
  belongs_to :origin_warehouse, class_name: "Warehouse", foreign_key: :origin_warehouse_id
  belongs_to :destination_warehouse, class_name: "Warehouse", foreign_key: :destination_warehouse_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :buyer
  has_one :seller
  has_many :stocks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  belongs_to :stock
  has_many :warehouse_stocks
end

app/models/warehouse_stock.rb
class WarehouseStock < ActiveRecord::Base
  belongs_to :stock
  belongs_to :product
  belongs_to :warehouse
end

app/controllers/warehouse_stocks_controller.rb
class WarehouseStocksController < ApplicationController
  before_action :set_warehouse_stock, only: [:show, :edit, :update, :destroy]

  # GET /warehouse_stocks
  # GET /warehouse_stocks.json
  def index
    @warehouse_stocks = WarehouseStock.all
  end

  # GET /warehouse_stocks/1
  # GET /warehouse_stocks/1.json
  def show
  end

  # GET /warehouse_stocks/new
  def new
    @warehouse_stock = WarehouseStock.new
  end

  # GET /warehouse_stocks/1/edit
  def edit
  end

  # POST /warehouse_stocks
  # POST /warehouse_stocks.json
  def create
    @warehouse_stock = WarehouseStock.new(warehouse_stock_params)

    respond_to do |format|
      if @warehouse_stock.save
        format.html { redirect_to @warehouse_stock, notice: 'Warehouse stock was successfully created.' }
        format.json { render :show, status: :created, location: @warehouse_stock }
      else
        format.html { render :new }
        format.json { render json: @warehouse_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouse_stocks/1
  # PATCH/PUT /warehouse_stocks/1.json
  def update
    respond_to do |format|
      if @warehouse_stock.update(warehouse_stock_params)
        format.html { redirect_to @warehouse_stock, notice: 'Warehouse stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @warehouse_stock }
      else
        format.html { render :edit }
        format.json { render json: @warehouse_stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouse_stocks/1
  # DELETE /warehouse_stocks/1.json
  def destroy
    @warehouse_stock.destroy
    respond_to do |format|
      format.html { redirect_to warehouse_stocks_url, notice: 'Warehouse stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse_stock
      @warehouse_stock = WarehouseStock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def warehouse_stock_params
      params.require(:warehouse_stock).permit(:stock_id, :warehouse_id, :product_id, :quantity)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/warehouse_stocks_helper.rb
module WarehouseStocksHelper
end

app/views/warehouse_stocks/_form.html.haml
= form_for @warehouse_stock do |f|
  - if @warehouse_stock.errors.any?
    #error_explanation
      %h2= "#{pluralize(@warehouse_stock.errors.count, "error")} prohibited this warehouse_stock from being saved:"
      %ul
        - @warehouse_stock.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :stock_id
    = f.number_field :stock_id
  .field
    = f.label :warehouse_id
    = f.number_field :warehouse_id
  .field
    = f.label :product_id
    = f.number_field :product_id
  .field
    = f.label :quantity
    = f.number_field :quantity
  .actions
    = f.submit 'Save'

app/views/warehouse_stocks/edit.html.haml
%h1 Editing warehouse_stock

= render 'form'

= link_to 'Show', @warehouse_stock
\|
= link_to 'Back', warehouse_stocks_path

app/views/warehouse_stocks/index.html.haml
%h1 Listing warehouse_stocks

%table
  %thead
    %tr
      %th Stock
      %th Warehouse
      %th Product
      %th Quantity
      %th
      %th
      %th

  %tbody
    - @warehouse_stocks.each do |warehouse_stock|
      %tr
        %td= warehouse_stock.stock_id
        %td= warehouse_stock.warehouse_id
        %td= warehouse_stock.product_id
        %td= warehouse_stock.quantity
        %td= link_to 'Show', warehouse_stock
        %td= link_to 'Edit', edit_warehouse_stock_path(warehouse_stock)
        %td= link_to 'Destroy', warehouse_stock, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Warehouse stock', new_warehouse_stock_path

app/views/warehouse_stocks/new.html.haml
%h1 New warehouse_stock

= render 'form'

= link_to 'Back', warehouse_stocks_path

app/views/warehouse_stocks/show.html.haml
%p#notice= notice

%p
  %b Stock:
  = @warehouse_stock.stock_id
%p
  %b Warehouse:
  = @warehouse_stock.warehouse_id
%p
  %b Product:
  = @warehouse_stock.product_id
%p
  %b Quantity:
  = @warehouse_stock.quantity

= link_to 'Edit', edit_warehouse_stock_path(@warehouse_stock)
\|
= link_to 'Back', warehouse_stocks_path