config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :order_items
  resources :orders
  resources :buyers
  resources :stock_transactions
  resources :warehouse_stocks
  resources :warehouses
  resources :stock_members
  resources :stocks
  resources :categories
  resources :products
  resources :sellers

  mount MailsViewer::Engine => '/delivered_mails'

  root 'home#index'

  devise_for :users

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  belongs_to :user

  has_many :buyers
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :seller
  belongs_to :buyer

  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :seller

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :seller
  belongs_to :category

  has_many :order_items
  has_many :stock_transactions
  has_many :warehouse_stocks
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  belongs_to :user

  has_many :orders
  has_many :order_items
  has_many :products
  has_many :stock_members
  has_many :stock_transactions
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user

  has_many :stock_members
  has_many :warehouses
  has_many :warehouse_stocks
end

app/models/stock_member.rb
class StockMember < ActiveRecord::Base
  belongs_to :stock
  belongs_to :seller
end

app/models/stock_transaction.rb
class StockTransaction < ActiveRecord::Base
  belongs_to :seller
  belongs_to :product
  belongs_to :origin_warehouse, class_name: "Warehouse", foreign_key: :origin_warehouse_id
  belongs_to :destination_warehouse, class_name: "Warehouse", foreign_key: :destination_warehouse_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :buyer
  has_one :seller
  has_many :stocks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  belongs_to :stock
  has_many :warehouse_stocks
end

app/models/warehouse_stock.rb
class WarehouseStock < ActiveRecord::Base
  belongs_to :stock
  belongs_to :product
  belongs_to :warehouse
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= category.description
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name
%p
  %b Description:
  = @category.description

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path