config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :order_items
  resources :orders
  resources :buyers
  resources :stock_transactions
  resources :warehouse_stocks
  resources :warehouses
  resources :stock_members
  resources :stocks
  resources :categories
  resources :products
  resources :sellers

  mount MailsViewer::Engine => '/delivered_mails'

  root 'home#index'

  devise_for :users

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
  belongs_to :user

  has_many :buyers
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :seller
  belongs_to :buyer

  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :seller

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :seller
  belongs_to :category

  has_many :order_items
  has_many :stock_transactions
  has_many :warehouse_stocks
end

app/models/seller.rb
class Seller < ActiveRecord::Base
  belongs_to :user

  has_many :orders
  has_many :order_items
  has_many :products
  has_many :stock_members
  has_many :stock_transactions
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  belongs_to :user

  has_many :stock_members
  has_many :warehouses
  has_many :warehouse_stocks
end

app/models/stock_member.rb
class StockMember < ActiveRecord::Base
  belongs_to :stock
  belongs_to :seller
end

app/models/stock_transaction.rb
class StockTransaction < ActiveRecord::Base
  belongs_to :seller
  belongs_to :product
  belongs_to :origin_warehouse, class_name: "Warehouse", foreign_key: :origin_warehouse_id
  belongs_to :destination_warehouse, class_name: "Warehouse", foreign_key: :destination_warehouse_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :buyer
  has_one :seller
  has_many :stocks

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  belongs_to :stock
  has_many :warehouse_stocks
end

app/models/warehouse_stock.rb
class WarehouseStock < ActiveRecord::Base
  belongs_to :stock
  belongs_to :product
  belongs_to :warehouse
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: [:show, :edit, :update, :destroy]

  # GET /warehouses
  # GET /warehouses.json
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1
  # GET /warehouses/1.json
  def show
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses
  # POST /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to @warehouse, notice: 'Warehouse was successfully created.' }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1
  # PATCH/PUT /warehouses/1.json
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to @warehouse, notice: 'Warehouse was successfully updated.' }
        format.json { render :show, status: :ok, location: @warehouse }
      else
        format.html { render :edit }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1
  # DELETE /warehouses/1.json
  def destroy
    @warehouse.destroy
    respond_to do |format|
      format.html { redirect_to warehouses_url, notice: 'Warehouse was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def warehouse_params
      params.require(:warehouse).permit(:name, :stock_id, :region, :adress, :size)
    end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/warehouses/_form.html.haml
= form_for @warehouse do |f|
  - if @warehouse.errors.any?
    #error_explanation
      %h2= "#{pluralize(@warehouse.errors.count, "error")} prohibited this warehouse from being saved:"
      %ul
        - @warehouse.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :stock_id
    = f.number_field :stock_id
  .field
    = f.label :region
    = f.text_field :region
  .field
    = f.label :adress
    = f.text_field :adress
  .field
    = f.label :size
    = f.number_field :size
  .actions
    = f.submit 'Save'

app/views/warehouses/edit.html.haml
%h1 Editing warehouse

= render 'form'

= link_to 'Show', @warehouse
\|
= link_to 'Back', warehouses_path

app/views/warehouses/index.html.haml
%h1 Listing warehouses

%table
  %thead
    %tr
      %th Name
      %th Stock
      %th Region
      %th Adress
      %th Size
      %th
      %th
      %th

  %tbody
    - @warehouses.each do |warehouse|
      %tr
        %td= warehouse.name
        %td= warehouse.stock_id
        %td= warehouse.region
        %td= warehouse.adress
        %td= warehouse.size
        %td= link_to 'Show', warehouse
        %td= link_to 'Edit', edit_warehouse_path(warehouse)
        %td= link_to 'Destroy', warehouse, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Warehouse', new_warehouse_path

app/views/warehouses/new.html.haml
%h1 New warehouse

= render 'form'

= link_to 'Back', warehouses_path

app/views/warehouses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @warehouse.name
%p
  %b Stock:
  = @warehouse.stock_id
%p
  %b Region:
  = @warehouse.region
%p
  %b Adress:
  = @warehouse.adress
%p
  %b Size:
  = @warehouse.size

= link_to 'Edit', edit_warehouse_path(@warehouse)
\|
= link_to 'Back', warehouses_path